# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0206a9ef1660b132d6c7f8a91bfc930a269527570b70d942518e099d312ddc305732acde09ee6373bc0409ad503ee04cee2dc3fd63514912239bd42da581b2ee

test:
  secret_key_base: 062147ad006d91370edd628946a067ec133e3d8d638bd623d3cc1bf70245a9e97883daa6b650063c4117a2d585b6a7b8fde72cce00d8996d1f561fd7d576f9fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
